# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17bf5958410497bbd15024607e332fe3dcfe8718ed913c31f62e83548805f3520de5e86e7ebfebe456212e089dce3fa4f584827e0e6d240e8ed11bb077cd6cec

test:
  secret_key_base: 4c2805cd28177952e14104de60e00fc63b48839dc90d6bddf5d52233e8c7e5ecdaf0684caea3e9be8efde88c66f961a22057f45cabff5e71ada041a77084a320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
